apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clustergroup-gitops
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: apps
  postBuild:
    substituteFrom:
      - kind: Secret
        name: kapp-flux-repo
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: kapp-flux